plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/ingsis-printScript/printscript")
        credentials {
            username = findProperty("gpr.user")
                    ?: System.getenv("GPR_USER")
                    ?: System.getenv("GITHUB_ACTOR")
            password = findProperty("gpr.key")
                    ?: System.getenv("GPR_KEY")
                    ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation "org.example:integration:0.1.159"
    implementation 'org.example:common:0.1.159'
    implementation 'org.example:interpreter:0.1.159'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
