plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/ingsis-printScript/printscript")
        credentials {
            username = findProperty("gpr.user") as String
                    ?: System.getenv("GITHUB_ACTOR")

            password = findProperty("gpr.key") as String
                    ?: System.getenv("GITHUB_TOKEN")
        }


    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation "org.example:integration:latest.release"
    implementation "org.example:common:latest.release"
    implementation "org.example:interpreter:latest.release"
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
